Repository X-lab2017/github-analysis-report-2019, pull requests merged in 2020-01, with the labels that each got.

#3 add 1201-1300 chinese project
  chinese
Labels: pull/approved

#4 update chinese
  chinese
Labels: pull/approved

#6 add chinese company from maxchen
  chinese
Labels: pull/approved

#8 add chinese top 500
  chinese
Labels: pull/approved

#9 add chinese-top500-1000
  chinese
Labels: pull/approved

#5 update Chinese projects in 1001-1100
  chinese
Labels: pull/approved

#10 feature: add expert comments
  REPORT.md
Labels: kind/feature, pull/approved

#7 add:new projects in chinese
  chinese
Labels: pull/approved

#12 fix: update company datas
  chinese_company
  static/chinese_top_20_act.png
  static/company_top_act.png
Labels: kind/bug, pull/approved

#15 refactor: change will-ww login
  .github/hypertrons.json
Labels: kind/enhancement

#13 add language_analysis
  REPORT.md
  static/china_opensource_project_language.png
  static/world_active_project_language.png
  static/world_participant_project_language.png
Labels: pull/approved
